name: Ping Application

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping application
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "https://chatbot-remember.onrender.com/")
          if [ "$response" -eq 200 ]; then
            echo "Ping successful (HTTP $response)"
          else
            echo "Ping failed (HTTP $response)"
            exit 1
          fi
